name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    - name: Build project
      run: cargo build --release

    - name: Run (basic test)
      run: cargo run --release -- https://rpc.gnosischain.com
